Us carrousel trending
WildCodeSchool-2024-02/JS-RemoteFR-CodeOfWar-P2-CineWild pull request #9
Opened 2024-07-01 14:17 UTC by Davido91390

2024-07-01 14:22 UTC, PixelKata approved these changes
parfait

2024-07-02 07:40 UTC, kpeset requested changes

2024-07-02 07:40 UTC, kpeset commented on client/src/styles/randomMovie.css
> +  background-color: var(#ff7e6b);
ça faut refaire :)
Une var a un nom, pas une valeur ^^

2024-07-02 07:59 UTC, Davido91390 commented on client/src/styles/randomMovie.css
> +  background-color: var(#ff7e6b);
Merci a toi j'avais pas fait attention ! Je viens de corriger

2024-07-02 14:11 UTC, kpeset approved these changes
C'est bon pour moi :)

2024-07-02 14:12 UTC, merged